### ISSUE TITLE
Gem Removed from Rubygems.org

### ISSUE THREAD

**Issue by drubin** [snap-ci/snap-deploy#13]
The readme says you can install the gem via RubyGems but it isn't on rubygems.org any more.

What is the correct way to install this gem, also can we update the readme please?

https://rubygems.org/gems/snap_deploy

**Comment by akshaykarle** [comment]
Hey @drubin the gem is now available again. You should be able to use the same method mentioned in the read me to get the gem. Thanks for pointing that out.
