### ISSUE TITLE
snap_deploy is not available in gems

### ISSUE THREAD

**Issue by nikita-leonov** [snap-ci/snap-deploy#5]

**Comment by ketan** [comment]
@nikita-leonov, any particular reason you would like to see this deployed to rubygems? It does not work outside of snap because it needs a lot of snap specific environments.

I'm just trying to understand the situation better.

**Comment by nikita-leonov** [comment]
We were looking to leverage snap_deploy in our go.cd environment. Current installation instructions provided in README.md are confusing, as makes it looks like snap_deploy available globally, but not as a local gem.

**Comment by ketan** [comment]
Thanks for that explanation.

snap-deploy is currently meant to be used standalone on snap-ci.com. That said, there's no reason it cant be added to the gemfile or installed via `sudo gem install` (pending publish to rubygems.org)

You may want to [look here](https://github.com/snap-ci/snap-deploy/blob/master/lib/snap_deploy/helpers.rb) before using this on go.cd, if you could supply a PR, I'm happy to push this out as a gem, that way you'll continue to get upgrades when we add more deploy capabilities :)

**Comment by nikita-leonov** [comment]
Thanks for that explanation. :) We actually decided to look around for more generic deployment solution, as our needs does not really match needs of snap-ci users. 
Meanwhile It is very unfortunate that snap-ci and go.cd projects developed by the same company have the same needs but solving them differently with a double effort. Hopefully at some point there will be more synergy between snap-ci and go.cd teams.

**Comment by ketan** [comment]
The needs of snap users are generally simpler than that of go.cd users for the most part. And our tools reflect that. If you're looking for something with capabilities to deploy to more cloud providers - you may checkout travis's DPL (but then again, it's tied to travis environment variables)

I'll mark this issue as closed.
